# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-09 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyRiskFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldName', models.CharField(max_length=100)),
                ('fieldType', models.CharField(choices=[('text', 'text'), ('date', 'date'), ('number', 'number'), ('enum', 'enum')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyRiskTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riskName', models.CharField(max_length=100)),
                ('companyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RiskTypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.CompanyRiskTypes')),
            ],
        ),
        migrations.CreateModel(
            name='UserDateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DateField()),
                ('CompanyRiskFieldsID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.CompanyRiskFields')),
                ('companyUserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.CompanyUser')),
            ],
        ),
        migrations.CreateModel(
            name='UserEnumData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('CompanyRiskFieldsID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.CompanyRiskFields')),
                ('companyUserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.CompanyUser')),
            ],
        ),
        migrations.CreateModel(
            name='UserEnumOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('EnumID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.UserEnumData')),
            ],
        ),
        migrations.CreateModel(
            name='UserNumberData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('CompanyRiskFieldsID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.CompanyRiskFields')),
                ('companyUserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.CompanyUser')),
            ],
        ),
        migrations.CreateModel(
            name='UserTextData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('CompanyRiskFieldsID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.CompanyRiskFields')),
                ('companyUserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.CompanyUser')),
            ],
        ),
        migrations.AddField(
            model_name='companyriskfields',
            name='RiskTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.CompanyRiskTypes'),
        ),
    ]
