# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-12 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userenumoption',
            name='EnumID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.CompanyRiskFields'),
        ),
    ]
